#include <iostream>
#include <exception>

using namespace std;
class MyException 
{
public:
char * what () 
{
cout<<"C++ Exception";
return 0;
}
};

int main() 
{
try 
{
throw MyException();
}
catch(MyException e) 
{
cout << "MyException caught" <<endl;
cout << e.what() <<endl;
}
return 0;
}

